services:
  paustian_pmci_module.container.link_container:
    class: Paustian\PMCIModule\Container\LinkContainer
    arguments:
      - "@translator.default"
      - "@router"
      - "@zikula_permissions_module.api.permission"
    tags:
      - { name: zikula.link_container }

  paustian_pmci_module.form.analysis_type:
    class: Paustian\PMCIModule\Form\Analysis
    arguments:
      - "@translator.default"
    tags:
      - { name: form.type }

  paustian_pmci_module.form.person_type:
      class: Paustian\PMCIModule\Form\Person
      arguments:
        - "@translator.default"
      tags:
        - { name: form.type }

  paustian_pmci_module.form.Survey_type:
      class: Paustian\PMCIModule\Form\Survey
      arguments:
        - "@translator.default"
      tags:
        - { name: form.type }

  paustian_pmci_module.form.surveyupload_type:
    class: Paustian\PMCIModule\Form\SurveyUpload
    arguments:
      - "@translator.default"
    tags:
      - { name: form.type }
